### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by shahkeyur** [dotenv-org/cli#12]
Hello Team,

I was looking up for cli tool for dotenv and luckily came across this. A few months back I had issues while syncing data between multiple PC and with my team members. It's important to have versioning as well in a well-maintained system. At that time I didn't find any tool that could fit my needs. The closest tool I could find was envault, so I started planning to build a service that could be advanced and easy to use for devs. Fortunately, Env Sync has already achieved what was on my mind.

I believe there are still more features that take the dotenv to next level.

I am trying to see here, how can I contribute to this project. What are the milestones? Is this community looking for other developers to help?  

I am more than willing to help, and I believe in a year it will change how enterprises handle their envs as env sync gets popular.

Thanks to everyone who has contributed to this project.

**Comment by motdotla** [comment]
Hi, Shahkeyur, thanks for reaching out and the kind words. 

Were you able to install the cli?

**Comment by shahkeyur** [comment]
Hi @motdotla, yes, I was able to install cli and do some quick tests around. The heroku and circleCI integrations are awesome!

**Comment by motdotla** [comment]
Glad to hear @shahkeyur. Closing this and as you run into issues or feature requests, go ahead and create those. Then maybe you can help contribute as well.
