### ISSUE TITLE
How does dotenv sync work?

### ISSUE THREAD

**Issue by mathiasfoster** [dotenv-org/cli#15]
I've been accepted to the Beta for Dotenv Sync, but I'm reluctant to use it until I understand more about how it works.

- How do you ensure that others can't access my secrets?
- How are secrets shared across machines?

**Comment by motdotla** [comment]
Hi @mathiasfoster:

Documentation has come together.

Here is a Security Overview: https://docs.dotenv.org/v1/security/overview

And here is documentation on the various security aspects of Dotenv Sync: https://docs.dotenv.org/v1

<img width="942" alt="Screen Shot 2021-11-29 at 8 23 32 PM" src="https://user-images.githubusercontent.com/3848/143985379-0ab7bc7c-4314-4191-a574-27993338496a.png">
