### ISSUE TITLE
UI: Error 500 on key remove

### ISSUE THREAD

**Issue by ajmnz** [dotenv-org/cli#27]
Hey 👋

I don't know if this is the right channel to report this, but I'm getting an internal server error every time I try to remove a key via the UI. Happens on every key, no matter the environment.

```json
{
  "errors": [
    {
      "code": null,
      "status": 500,
      "message": "internal server error."
    }
  ]
}
```

**Comment by ajmnz** [comment]
Just got the follow-up via email, thanks!

**Comment by motdotla** [comment]
Yep, small UI bug. Thanks for finding. It was not a security risk. All patched up.
